version: '3.7'

services:
  db:
    image: mongo
    container_name: mindx-hackathon-db
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

  app:
    image: node:lts
    container_name: mindx-hackathon-app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - '3000:3000'

volumes:
  node_modules:
  db:
